In [6]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn. linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Naive Bayes
from sklearn.naive_bayes import GaussianNB

#ANN and RNN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



In [7]:
df=pd.read_csv("C:/Users/ragha/OneDrive/Desktop/Ethics/Heart_Disease_Prediction.csv")

In [47]:
df.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium Heart Disease  
0                        3         3      Presence  
1                        0         7       Absence  
2                        0         7      Presence  
3                        1         7       Absence  
4                        1         3       Absence

In [17]:
df.shape

(270, 14)

In [18]:
df.isna().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [8]:
df['Heart Disease']=df['Heart Disease'].map({ 'Presence' : 1, 'Absence' : 0})
df.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium  Heart Disease  
0                        3         3              1  
1                        0         7              0  
2                        0         7              1  
3                        1         7              0  
4                        1         3              0

In [9]:
x=df.drop(['Heart Disease' ] ,axis=1) 
y=df[ 'Heart Disease' ]

In [10]:
pca=PCA(13)
x_pca=pca.fit_transform(x)
x_pca.shape

(270, 13)

In [44]:
xtrain_pca, xtest_pca, ytrain,ytest=train_test_split(x_pca,y,test_size=0.4,random_state=11)

In [45]:
def report(actual,pred) :
    acc_score=accuracy_score(actual, pred)
    con_mat=confusion_matrix(actual, pred )
    class_rep=classification_report(actual,pred) 
    print("Accuracy of model is", round((acc_score*100),2),'%')
    print( '\n',con_mat) 
    print( ' \n ' , class_rep)

In [47]:
log=LogisticRegression(max_iter=1000) 
log.fit(xtrain_pca,ytrain) 
train_log=log.predict (xtrain_pca) 
test_log=log. predict (xtest_pca )
# report(ytrain,train_log) 
report (ytest, test_log)
log.score(xtest_pca, ytest)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, test_log)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, test_log))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 88.89 %

 [[60  4]
 [ 8 36]]
 
                precision    recall  f1-score   support

           0       0.88      0.94      0.91        64
           1       0.90      0.82      0.86        44

    accuracy                           0.89       108
   macro avg       0.89      0.88      0.88       108
weighted avg       0.89      0.89      0.89       108

Mean Absolute Error (MAE): 0.1111111111111111
Root Mean Square Error (RMSE): 0.3333333333333333


In [48]:
dt=DecisionTreeClassifier(max_depth=7,min_samples_split=17,min_samples_leaf=10)
dt.fit (xtrain_pca, ytrain) 
pred_dtree_train=dt.predict(xtrain_pca) 
pred_dtree_test=dt.predict (xtest_pca ) 
# report(ytrain,pred_dtree_train) 
report (ytest, pred_dtree_test )
dt.score(xtest_pca, ytest)
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, pred_dtree_test)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, pred_dtree_test))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 82.41 %

 [[57  7]
 [12 32]]
 
                precision    recall  f1-score   support

           0       0.83      0.89      0.86        64
           1       0.82      0.73      0.77        44

    accuracy                           0.82       108
   macro avg       0.82      0.81      0.81       108
weighted avg       0.82      0.82      0.82       108

Mean Absolute Error (MAE): 0.17592592592592593
Root Mean Square Error (RMSE): 0.41943524640393054


In [49]:
rf=RandomForestClassifier( n_estimators=15 , max_depth=4, min_samples_split=15,random_state=786)
rf.fit(xtrain_pca,ytrain) 
train_rf=rf.predict(xtrain_pca)  
test_rf=rf.predict (xtest_pca) 
# report(ytrain,train_rf) 
report (ytest, test_rf)
rf.score(xtest_pca, ytest)
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, test_rf)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, test_rf))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 80.56 %

 [[58  6]
 [15 29]]
 
                precision    recall  f1-score   support

           0       0.79      0.91      0.85        64
           1       0.83      0.66      0.73        44

    accuracy                           0.81       108
   macro avg       0.81      0.78      0.79       108
weighted avg       0.81      0.81      0.80       108

Mean Absolute Error (MAE): 0.19444444444444445
Root Mean Square Error (RMSE): 0.44095855184409843


In [50]:
svm_ = SVC(kernel='linear', random_state=0)  
svm_.fit(xtrain_pca, ytrain)
train_svm_=svm_.predict(xtrain_pca)  
test_svm_=svm_.predict (xtest_pca) 
# report(ytrain,train_svm_) 
report (ytest, test_svm_)
svm_.score(xtest_pca, ytest)
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, test_svm_)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, test_svm_))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 87.04 %

 [[56  8]
 [ 6 38]]
 
                precision    recall  f1-score   support

           0       0.90      0.88      0.89        64
           1       0.83      0.86      0.84        44

    accuracy                           0.87       108
   macro avg       0.86      0.87      0.87       108
weighted avg       0.87      0.87      0.87       108

Mean Absolute Error (MAE): 0.12962962962962962
Root Mean Square Error (RMSE): 0.3600411499115478


In [51]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(xtrain_pca,ytrain)
train_knn=knn.predict(xtrain_pca)  
test_knn=knn.predict (xtest_pca) 
# report(ytrain,train_knn) 
report (ytest, test_knn)
knn.score(xtest_pca,ytest)
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, test_knn)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, test_knn))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 65.74 %

 [[53 11]
 [26 18]]
 
                precision    recall  f1-score   support

           0       0.67      0.83      0.74        64
           1       0.62      0.41      0.49        44

    accuracy                           0.66       108
   macro avg       0.65      0.62      0.62       108
weighted avg       0.65      0.66      0.64       108

Mean Absolute Error (MAE): 0.3425925925925926
Root Mean Square Error (RMSE): 0.5853140973807077


In [52]:
import math
math.sqrt(len(ytest))

10.392304845413264

In [53]:
nb = GaussianNB()
nb.fit(xtrain_pca, ytrain)
test_nb=nb.predict (xtest_pca) 
report (ytest, test_nb)
nb.score(xtest_pca,ytest)
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, test_nb)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, test_nb))
print(f'Root Mean Square Error (RMSE): {rmse}')

Accuracy of model is 87.04 %

 [[57  7]
 [ 7 37]]
 
                precision    recall  f1-score   support

           0       0.89      0.89      0.89        64
           1       0.84      0.84      0.84        44

    accuracy                           0.87       108
   macro avg       0.87      0.87      0.87       108
weighted avg       0.87      0.87      0.87       108

Mean Absolute Error (MAE): 0.12962962962962962
Root Mean Square Error (RMSE): 0.3600411499115478


In [54]:
# Define the Artificial Neural Network (ANN)
model_ann = Sequential([
    Dense(64, activation='relu', input_dim=xtrain_pca.shape[1]),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model_ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model_ann.fit(xtrain_pca, ytrain, epochs=50, batch_size=16, validation_data=(xtest_pca, ytest), verbose=2)

# Evaluate the model
y_pred_ann_prob = model_ann.predict(xtest_pca)
y_pred_ann = (y_pred_ann_prob > 0.5).astype(int)
# y_pred_ann = model_ann.predict_classes(xtest_pca)

report (ytest, y_pred_ann)
loss_ann, accuracy_ann = model_ann.evaluate(xtest_pca, ytest)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, y_pred_ann)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, y_pred_ann))
print(f'Root Mean Square Error (RMSE): {rmse}')

Epoch 1/50
11/11 - 1s - loss: 2.1711 - accuracy: 0.5309 - val_loss: 1.3209 - val_accuracy: 0.6111 - 579ms/epoch - 53ms/step
Epoch 2/50
11/11 - 0s - loss: 0.9611 - accuracy: 0.6420 - val_loss: 0.8403 - val_accuracy: 0.5926 - 48ms/epoch - 4ms/step
Epoch 3/50
11/11 - 0s - loss: 0.7525 - accuracy: 0.6728 - val_loss: 0.7034 - val_accuracy: 0.6389 - 46ms/epoch - 4ms/step
Epoch 4/50
11/11 - 0s - loss: 0.6105 - accuracy: 0.6914 - val_loss: 0.6309 - val_accuracy: 0.7315 - 43ms/epoch - 4ms/step
Epoch 5/50
11/11 - 0s - loss: 0.5527 - accuracy: 0.7160 - val_loss: 0.6137 - val_accuracy: 0.7407 - 43ms/epoch - 4ms/step
Epoch 6/50
11/11 - 0s - loss: 0.5290 - accuracy: 0.7099 - val_loss: 0.5604 - val_accuracy: 0.7500 - 44ms/epoch - 4ms/step
Epoch 7/50
11/11 - 0s - loss: 0.4981 - accuracy: 0.7469 - val_loss: 0.5626 - val_accuracy: 0.7778 - 45ms/epoch - 4ms/step
Epoch 8/50
11/11 - 0s - loss: 0.4706 - accuracy: 0.7963 - val_loss: 0.5502 - val_accuracy: 0.7685 - 44ms/epoch - 4ms/step
Epoch 9/50
11/11 - 0s 

In [55]:
xtrain_rnn = xtrain_pca.reshape((xtrain_pca.shape[0], 1, xtrain_pca.shape[1]))
xtest_rnn = xtest_pca.reshape((xtest_pca.shape[0], 1, xtest_pca.shape[1]))

# Define the Recurrent Neural Network (RNN)
model_rnn = Sequential([
    tf.keras.layers.SimpleRNN(32, activation='relu', input_shape=(xtrain_rnn.shape[1], xtrain_rnn.shape[2])),
    Dense(1, activation='sigmoid')
])

# Compile the model
model_rnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model_rnn.fit(xtrain_rnn, ytrain, epochs=50, batch_size=16, validation_data=(xtest_rnn, ytest), verbose=2)

# Evaluate the model
y_pred_rnn_prob = model_rnn.predict(xtest_rnn)
y_pred_rnn = (y_pred_rnn_prob > 0.5).astype(int)

report (ytest, y_pred_rnn)
accuracy_rnn = model_rnn.evaluate(xtest_rnn, ytest)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(ytest, y_pred_rnn)
print(f'Mean Absolute Error (MAE): {mae}')

# Calculate Root Mean Square Error (RMSE)
rmse = np.sqrt(mean_squared_error(ytest, y_pred_rnn))
print(f'Root Mean Square Error (RMSE): {rmse}')

Epoch 1/50
11/11 - 1s - loss: 3.9623 - accuracy: 0.5123 - val_loss: 4.3205 - val_accuracy: 0.3426 - 895ms/epoch - 81ms/step
Epoch 2/50
11/11 - 0s - loss: 2.8521 - accuracy: 0.5247 - val_loss: 3.3568 - val_accuracy: 0.4444 - 53ms/epoch - 5ms/step
Epoch 3/50
11/11 - 0s - loss: 2.0670 - accuracy: 0.5309 - val_loss: 2.5915 - val_accuracy: 0.4259 - 47ms/epoch - 4ms/step
Epoch 4/50
11/11 - 0s - loss: 1.5643 - accuracy: 0.5494 - val_loss: 2.0548 - val_accuracy: 0.4537 - 49ms/epoch - 4ms/step
Epoch 5/50
11/11 - 0s - loss: 1.2209 - accuracy: 0.5741 - val_loss: 1.6317 - val_accuracy: 0.5000 - 48ms/epoch - 4ms/step
Epoch 6/50
11/11 - 0s - loss: 0.9618 - accuracy: 0.6173 - val_loss: 1.3328 - val_accuracy: 0.5185 - 49ms/epoch - 4ms/step
Epoch 7/50
11/11 - 0s - loss: 0.7919 - accuracy: 0.6605 - val_loss: 1.1440 - val_accuracy: 0.5648 - 51ms/epoch - 5ms/step
Epoch 8/50
11/11 - 0s - loss: 0.6893 - accuracy: 0.6605 - val_loss: 0.9844 - val_accuracy: 0.5926 - 49ms/epoch - 4ms/step
Epoch 9/50
11/11 - 0s 